spring:
  h2:
    console:
      enabled: true
#  datasource:
#    url: jdbc:h2:mem:mydb
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver
  datasource:
    url: jdbc:mysql://u2s8s3qafpbq2lar:ntutElh5kX0wOvfyrUMD@bmg8dkwpjwqg83wtflkt-mysql.services.clever-cloud.com:3306/bmg8dkwpjwqg83wtflkt
    driverClassName: com.mysql.cj.jdbc.Driver
    username: u2s8s3qafpbq2lar
    password: ntutElh5kX0wOvfyrUMD
#    url: jdbc:mysql://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
#    driverClassName: com.mysql.cj.jdbc.Driver
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
#    database-platform: org.hibernate.dialect.H2Dialect
#    databasePlatform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher